import CartContext from '@/context/cartContext';
import './globals.css';
import { Inter } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Theme
					accentColor='crimson'
					grayColor='sand'
					radius='large'
					scaling='95%'>
					<CartContext>{children}</CartContext>
				</Theme>
			</body>
		</html>
	);
}
